version: '3.7'

services:
  postgres_pqc:
    container_name: 'pqc_database'
    image: postgres:12
    environment:
      # change this for a "real" app!
      POSTGRES_DB: pqc
      POSTGRES_USER: pqc
      POSTGRES_PASSWORD: pqc
    #volumes:
    #  - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - backend-network

  sonarqube:
    container_name: sonarqube
    image: sonarqube:8.9-community
    ports:
      - 8000:9000
    networks:
      - backend-network

networks:
  backend-network:
    name: backend
    driver: bridge
